#!/bin/bash
echo 'Begining compile'

# Renove old
echo 'Erasing old files'
rm bin/*
rm object/*

# ASM to BIN
echo 'Compiling assembly...'
nasm -f bin -o bin/boot.bin src/boot.asm
nasm -f bin -o bin/loader.bin src/loader.asm
nasm src/entry.asm -f elf32 -o object/entry.o

# C to BIN
echo 'Compiling C...'
gcc -ffreestanding -c -m32 src/kernel.c -o object/kernel.o
ld -melf_i386 -o bin/kernel.bin -Ttext 0x1000 object/entry.o object/kernel.o --oformat binary

# Combine
echo 'Combining all...'
cat bin/boot.bin bin/loader.bin  bin/kernel.bin > bin/os-image.bin

# Make Floppy
echo 'Creating floppy...'
dd status=noxfer conv=notrunc if=bin/os-image.bin of=os.flp

echo 'Compile complete'
