#!/bin/bash
set -e
echo 'Building THOS Version 0.1'

# Step 1: Removing Old Files
echo ' - Removing Old Files'
rm bin/*

# Step 2: Compiling Assembly Files
echo ' - Compiling Assembly Files'
nasm -f elf32 src/kernel.asm -o bin/kasm.o

# Step 3: Compiling C Files
echo ' - Compiling C Files'
gcc -m32 -c src/kernel.c -o bin/kc.o

# Step 4: Linking Files
echo ' - Linking Files'
ld -m elf_i386 -T src/link.ld -o bin/kernel bin/kasm.o bin/kc.o

# Step 4: Running Kernel in QEMU
echo ' - Running Kernel in QEMU'
qemu-system-i386 -kernel bin/kernel

